version: '3.1'

services:
  mysql-container:
    container_name: mysql-container
    image: mysql:oraclelinux9
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: http_dog
    volumes:
      - mysql-container:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network-external
    restart: unless-stopped
  phpmyadmin-container:
    container_name: phpmyadmin-container
    image: phpmyadmin:5.2.1-apache
    platform: linux/arm64/v8
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - phpmyadmin-container:/etc/phpmyadmin
    ports:
      - "5050:80"
    networks:
      - app-network-external
    restart: unless-stopped
    depends_on:
      - mysql-container
  http-dog-container:
    image: jayoswal20/http-dog:1.3.0
    container_name: http-dog-container
    platform: linux/arm64/v8
    ports:
      - "8080:8080"
    networks:
      - app-network-external
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - phpmyadmin-container

networks:
  app-network-external:
    driver: bridge
volumes:
  mysql-container:
  phpmyadmin-container:
